-- V2: Evolución del modelo relacional de Eventify
ALTER TABLE venues
    ADD COLUMN ciudad VARCHAR(100) NOT NULL;

ALTER TABLE events
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE events
    ADD COLUMN venue_id BIGINT NOT NULL;

CREATE TABLE categories(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500)
);

CREATE TABLE events_categories(
    event_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY(event_id, category_id),
    CONSTRAINT fk_events_categories_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fk_events_categories_category FOREIGN KEY (category_id) REFERENCES categories (id) );
