spring.application.name=semana_4

# Base de datos H2 persistente en archivo.
spring.datasource.url=jdbc:h2:file:./data/eventify
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate no crea ni modifica tablas automáticamente.
spring.jpa.hibernate.ddl-auto=none

# Muestra las consultas SQL ejecutadas por Hibernate.
spring.jpa.show-sql=true

# Formatea las consultas SQL para que sean más legibles.
spring.jpa.properties.hibernate.format_sql=true

# Activa Flyway para controlar las migraciones de la base de datos.
spring.flyway.enabled=true

# Habilita la consola web de H2.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console